### PR TITLE
List and Remove keys page

### LINKED ISSUE #99: add a page to list keys
create a page to list the user (ssh) keys

### PR DESCRIPTION
**Pull request by raphamorim**
Work in Progress, please don't merge yet.
Closes #99, #100

### CODE REVIEW

**Comment by raphamorim** [comment]
Guys, I'm having problems about tsuru API [/users/keys/{key}](https://github.com/tsuru/tsuru/blob/master/api/server.go#L203) route. 

Can anyone help me? 
cc @andrewsmedina , @tarsisazevedo

**Comment by tarsisazevedo** [comment]
@raphamorim what problem? if you want to, we have a gitter channel to discuss issues, gitter.im/tsuru/tsuru

**Comment by raphamorim** [comment]
### Page preview

screen shot 2016-06-28 at 14 37 11

**Comment by raphamorim** [comment]
Now this PR is available for review 👍

**Comment by andrewsmedina** [comment]
@raphamorim thank you!

**Comment by raphamorim** [comment]
@andrewsmedina :octocat:

**Pull request merged**
