### PR TITLE
Show app status in the dashboard app list

### PR DESCRIPTION
**Pull request by pauloalem**
@andrewsmedina We still miss nice images for the status

### CODE REVIEW

**Comment by tarsisazevedo** [comment]
@pauloalem an app can have several process and each process have your status. In your PR just one status is present. Can you update it?

**Comment by pauloalem** [comment]
@tarsisazevedo I remember raising this issue to @andrewsmedina and I think that we settled on just displaying one status because of *reasons*. I don't really remember them, though.
What would be the the alternative? How to display multiple statuses on that interface without cluttering it?
Tell me what you think would be ideal and I'll update it.

Also, it would be nice to have better icons for the statuses. The ones in this PR are kind of ugly. There was a designer who was supposed to create those for us, but hasn't.

**Comment by andrestc** [comment]
Maybe you could display the number of processes associated with each status. For example, `2 started` `1 error`. That way we limit the number of icons for each app by the number of possible states (controlled) because limiting it by the number of processes is out of our control. What do you think, @tarsisazevedo ?

**Comment by andrewsmedina** [comment]
Group units by status is a good way to go. But I believe that we don't need icons :)

**Comment by pauloalem** [comment]
@andrewsmedina but... pretty icons...

Ok, i'll update the PR

**Pull request closed without merging**
